### ISSUE TITLE
function ds_tree_build_node_value missing from current build

### ISSUE THREAD

**Issue by cicadian** [kemonologic/fuwafuwa#3]
Variable <unknown_object>.ds_tree_build_node_value(100037, -2147483648) not set before reading it.
 at gml_Script_timer_create (line 49) - 	var _timerNode = ds_tree_build_node_value(				 "TIME_START", _timeStart,
############################################################################################
gml_Script_timer_create (line 49)
gml_Object_oProj__Create_0 (line 3) - projectile_timer_lifespan = timer_create(3, time_start.s, false);
gml_Object_oProj_Rocket_MLRS_Create_0 (line 1)
gml_Object_oCursor_Step_0 (line 247)

**Comment by cicadian** [comment]
also missing dependent function is_even

**Comment by cicadian** [comment]
also missing dependent function normalize

**Comment by kemonologic** [comment]
Some heckin uwu beans told me it was problematic to normalize values so i left the function out. Closed as wontfix

**Comment by kemonologic** [comment]
Necessary functions are all either removed or (when necessary) included as utilities now

**Comment by kemonologic** [comment]
fixed as of 0.2.5. closed as DIDFIX
