### ISSUE TITLE
[Feature Request] timer_stop 

### ISSUE THREAD

**Issue by Manukineko** [kemonologic/fuwafuwa#31]
I've played with Time Sources, planning to switch to them, but I think FuwaFuwa is better.

I would like to know if adding a `timer_stop(timer, runScript)` method is possible?
I create a timer when I enter a state and destroy it when I leave this state, but I would like to just stop the timer without destroying it, so I can just start it again when I enter the state again.
Allowing to trigger the attached script or another callback when I do would be great, too.

What do you think?

**Comment by kemonologic** [comment]
I'm glad this library is still helpful! Just to clarify, what's the expected difference in behavior from `timer_pause` (outside of the script-running part)? Is it that it would reset progress like in `timer_restart` in addition to keeping the timer paused, or...? In that case it can be done by calling them sequentially, but obviously that's kinda inconvenient and could be rolled into a single function since timer reuse should be easy. Script-running on resume should be doable too.

Either way, if a `timer_stop` is added it'd probably be best to rename `timer_unpause` to `timer_resume` so the name makes more sense.

**Comment by Manukineko** [comment]
Oh yes it is still helpful : `timer_append` and `timer_set_duration` for the win !
My use case is that I use an `irandom_range` function as the time parameter and a script that append this same function with `timer_append`and then destroy the timer once I leaved the state.
With GM's Time Sources, you can't do that. I need to check if the Time Source  expired, then generate a new time in a variable with `irandom_range`, use the painful `time_source_reconfigure` to apply the new time which need also to set again all the same other parameters you set the first time with `time_source_create` and then start the time source again with `time_source_start`. The only usable thing was that I could call `tiler_source_reset` or `timer_source_stop` when I'd leave the state.

So that's just what I miss in fuwafuwa.

Regarding the behaviour, yes, `timer_stop` would reset the timer like in `timer_restart` and immediately paused it like in `timer_pause`, trigger the callback script if you want.
You then would call `timer_unpause` to run it again, but yeah, it should be rename to `timer_resume` I guess, or use `timer_restart` instead ?

True that `resume`, `restart`, `start`, `stop` and `pause` can be confusing because that all more or less the same XD

Another thought : to be consistent with `timer_stop`, maybe renaming `timer_create_paused` to `timer_create_stopped` would make more sense ? Then you use `timer_resume` to run it (the former `timer_unpause`)

I also noticed that Time Sources dissociated Reset and Stop : reset work on an expired time source so you can start the time source again while Stop reset only the time but not the repetition so if the time source was already expired, it won't go back to its original state. Maybe that's something to get inspiration of for the naming convention XD

**Comment by kemonologic** [comment]
🥳

**Comment by Manukineko** [comment]
Thank you \o/
